defaults:
  - temos
  - _self_

_target_: src.models.clatr.CLaTr

lmd:
  recons: 1.0
  latent: 1.0e-5
  kl: 1.0e-5
  contrastive: 0.1

lr: 1e-5
temperature: 0.1
threshold_selfsim: 0.995 # 0.99 = 2 * 0.995 - 1
threshold_selfsim_metrics: 0.995 # 0.99 = 2 * 0.995 - 1
log_wandb: ${log_wandb}