_target_: src.datasets.modalities.caption_dataset.CaptionDataset

defaults:
  - _self_
  - lm: clip

name: caption

dataset_dir: ${dataset.dataset_dir}
segment_dir: ${dataset.dataset_dir}/cam_segments
raw_caption_dir: ${dataset.dataset_dir}/caption_cam
feat_caption_dir: ${dataset.dataset_dir}/caption_cam_${dataset.caption.lm.lm_name}

num_segments: 27
num_cams: ${dataset.standardization.num_cams}